config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :patient_requests do
    resources :comments
  end
  resources :home
  devise_for :users
  root to: 'home#home', as: 'landing_page'

  get 'comments/:id/new' => 'comments#new', as: :new_comment_on_request

  # This is a blank app! Pick your first screen, build out the RCAV, and go from there. E.g.:

  # get "/your_first_screen" => "pages#first"
end

app/models/patient_request.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: patient_requests
#
#  id             :integer          not null, primary key
#  description    :text
#  image          :string
#  injury_type    :string
#  pain           :integer
#  queue_position :integer
#  rank           :integer
#  status         :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  user_id        :integer
#
class PatientRequest < ApplicationRecord
  resourcify
  belongs_to :user, required: true, class_name: 'User', foreign_key: 'user_id'
  has_many :comments, class_name: 'Comment', foreign_key: 'patient_request_id', dependent: :destroy
  has_one_attached :injury_photo

  validates :description, presence: true,
                          length: { maximum: 1000, too_long: '%<count>s characters is the maximum allowed' }

  INJURY_SCORES = {
    'minor' => 2,
    'moderate' => 5,
    'severe' => 8,
    'critical' => 10
  }.freeze

  def set_queue_position
    injury_score = INJURY_SCORES[injury_type] || 0
    # Define weights
    w_p = 1.0
    w_i = 2.0
    w_t = 0.1

    # Calculate time factor in hours
    time_now = Time.current
    time_difference = time_now - created_at
    time_factor = time_difference / 1.hour

    self.queue_position = (pain * w_p) + (injury_score * w_i) - (time_factor * w_t)
    save
  end

  # Class method to rank patients
  def self.rank_patients
    # Calculate queue positions for all patient requests
    all.each(&:set_queue_position) # Recalculate if necessary

    # Sort patients by queue position in descending order
    sorted_patients = all.order(queue_position: :desc)

    # Assign ranks
    sorted_patients.each_with_index do |patient, index|
      patient.update(rank: index + 1) # Update or add rank attribute
    end
  end

  def self.get_top
    top_patient = all.order(rank: :asc).first
    return nil unless top_patient # Return nil if there's no top patient

    top_patient.user.first_name
  end
end

app/controllers/patient_requests_controller.rb
# frozen_string_literal: true

class PatientRequestsController < ApplicationController
  before_action :set_patient_request, only: %i[show edit update destroy]
  before_action { authorize @patient_request || PatientRequest }
  # GET /patient_requests or /patient_requests.json
  def index
    @patient_requests = PatientRequest.rank_patients.paginate(page: params[:page], per_page: 12)
  end

  # GET /patient_requests/1 or /patient_requests/1.json
  def show; end

  # GET /patient_requests/new
  def new
    @patient_request = PatientRequest.new
  end

  # GET /patient_requests/1/edit
  def edit; end

  # POST /patient_requests or /patient_requests.json
  def create
    @patient_request = PatientRequest.new(patient_request_params)
    respond_to do |format|
      if @patient_request.save
        @patient_request.set_queue_position
        PatientRequest.rank_patients
        format.html do
          redirect_to patient_request_url(@patient_request), notice: 'Patient request was successfully created.'
        end
        format.json { render :show, status: :created, location: @patient_request }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patient_requests/1 or /patient_requests/1.json
  def update
    respond_to do |format|
      if @patient_request.update(patient_request_params)
        format.html do
          redirect_to patient_request_url(@patient_request), notice: 'Patient request was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @patient_request }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patient_requests/1 or /patient_requests/1.json
  def destroy
    @patient_request.destroy!

    respond_to do |format|
      format.html { redirect_to patient_requests_url, notice: 'Patient request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_patient_request
    @patient_request = PatientRequest.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def patient_request_params
    params.require(:patient_request).permit(:user_id, :description, :image, :status, :pain, :queue_position,
                                            :injury_type, :injury_photo)
  end
end

app/views/patient_requests/_form.html.erb
<%= render 'shared/breadcrumb', breadcrumb_pages: [{ name: "Home", url: landing_page_path }, {name: "Queue", url: patient_requests_path}, {name: "Form"}] %>
<%= form_with(model: patient_request, class: "container-fluid d-flex justify-content-center align-items-center vh-75 mt-5 mb-5") do |form| %>
  <div class="card p-4 shadow w-100 w-md-75 w-lg-50">
    <h1 class="card-title text-center mb-4">Patient Request</h1>
    <% if patient_request.errors.any? %>
      <div class="alert alert-danger">
        <h2><%= pluralize(patient_request.errors.count, "error") %> prohibited this patient request from being saved:</h2>
        <ul>
          <% patient_request.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div style="display: none;">
      <%= form.label :user_id %>
      <%= form.number_field :user_id, value: current_user.id, class: "form-control m-2 input-sm w-100" %>
    </div>

    <div class="form-group">
      <%= form.label :injury_photo %>
      <%= form.file_field :injury_photo, class: "form-control m-2 input-sm" %>
    </div>

    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, required: true, class: "form-control m-2 input-sm" %>
    </div>

    <div class="form-group">
      <%= form.label :pain %>
      <%= form.select :pain, options_for_select(1..10), required: true, class: "form-control m-2 input-sm w-100 w-sm-50 w-md-25" %>
    </div>

    <div class="form-group">
      <%= form.label :injury_type %>
      <%= form.select :injury_type, ['minor', 'moderate', 'severe', 'critical'], required: true, class: "form-control m-2 input-sm w-100" %>
    </div>

    <div style="display: none;">
      <%= form.label :status %>
      <%= form.text_field :status, value: "under review", class: "form-control m-2 input-sm w-100" %>
    </div>

    <div class="text-center">
      <%= form.submit "Submit", class: "btn btn-primary btn-lg btn-block mt-4" %>
      <%= link_to "Go to queue", patient_requests_path, class: "btn btn-primary btn-lg btn-block mt-4" %>
    </div>
  </div>
<% end %>

app/views/patient_requests/_patient_request.html.erb
<div id="<%= dom_id patient_request %>" class="patient-request mb-3">
  <div class="card border mx-auto text-center shadow-sm" style="max-width: 90%;">
    <h1 class="card-text text p-2" style="font-size: 1.5rem;"><%= patient_request.rank %></h1>
    <div class="card-body text">
      <strong class="card-title d-block" style="font-size: 1.25rem;">
        <%= patient_request.user.first_name + " " + patient_request.user.last_name %>
      </strong>
      <!-- Placeholder for Estimated Time -->
      <div class="estimated-time mt-2"></div>
      <% if policy(patient_request).show? %>
      <div class="card-body p-0 mt-3">
        <% if current_page?(patient_requests_path) %>
          <%= link_to "View details", patient_request, class: "btn btn-outline-dark btn-sm w-100 mb-2" %>
          <%= button_to "Remove from queue", patient_request, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-dark btn-sm w-100" %>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/patient_requests/edit.html.erb
<%= render "form", patient_request: @patient_request %>

app/views/patient_requests/index.html.erb
<%= render 'shared/breadcrumb', breadcrumb_pages: [{ name: "Home", url: landing_page_path }, {name: "Queue"}] %>
<section class="queue-section p-4">
  <div class="container text-center">
    <h1 class="mb-4">Emergency Room Queue</h1>
    
    <div class="d-flex justify-content-center align-items-center mb-4 flex-column">
      <div class="border border-primary rounded p-3" id="current-time">
        <%= User.display_time %>
      </div>
    </div>

    <% if PatientRequest.get_top %>
      <div class="alert alert-success p-3 mx-auto text-center" style="max-width: 600px; border-radius: 10px;">
        <h2 id="top-patient"><%= PatientRequest.get_top %>, you are next!</h2>
      </div>
    <% else %>
      <div class="alert alert-warning p-3">
        <h2>No patients are currently in the queue.</h2>
      </div>
    <% end %>
  </div>
</section>

<section class="cta-section text-center p-4">
  <div class="container">
    <h2>Need to join the queue?</h2>
    <p>If you have an emergency or need to join the queue, click the button below to get started.</p>
    <%= link_to "Join the Queue", new_patient_request_path, class: "btn btn-primary btn-lg" %>
  </div>
</section>

<div class="container">
  <div class="row p-2">
    <% @patient_requests.each do |patient_request| %>
      <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-3">
        <%= render patient_request %>
      </div>
    <% end %>
  </div>
  
  <div class="d-flex justify-content-center m-3">
    <%= will_paginate @patient_requests, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </div>
</div>

app/views/patient_requests/new.html.erb
<%= render "form", patient_request: @patient_request %>

app/views/patient_requests/show.html.erb
<%= render 'shared/breadcrumb', breadcrumb_pages: [{ name: "Home", url: landing_page_path }, {name: "Queue", url: patient_requests_path}, {name: "Details"}] %>
<div class="container-fluid">
  <div class="row justify-content-center p-3">
    <div class="col-12 col-md-10 col-lg-8">
      <div class="card text-center mb-3">
        <div class="card-body">
          <h1 class="card-title">Details for <%= @patient_request.user.first_name %></h1>
          <p class="card-text overflow-auto p-3">Description: <%= @patient_request.description %></p>
          <ul class="list-group list-group-flush text-dark">
            <li class="list-group-item">Status: <%= @patient_request.status %></li>
            <li class="list-group-item">Pain: <%= @patient_request.pain %></li>
            <li class="list-group-item">Injury Type: <%= @patient_request.injury_type %></li>
          </ul>
          <div class="d-flex flex-column flex-md-row justify-content-center align-items-center p-3">
            <!-- Button trigger modal -->
            <%= render partial: "shared/modal", locals: { patient_request: @patient_request } %>
            <button class="btn btn-primary btn-lg m-2" data-bs-toggle="modal" data-bs-target="#exampleModal">
              View Patient Image
            </button>
            <%= link_to "View Notes", patient_request_comments_path(@patient_request), class: "btn btn-primary btn-lg m-2" %>
            <%= link_to "Return to Queue", patient_requests_path, class: "btn btn-primary btn-lg m-2" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>