config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :patient_requests do
    resources :comments
  end
  resources :home
  devise_for :users
  root to: 'home#home', as: 'landing_page'

  get 'comments/:id/new' => 'comments#new', as: :new_comment_on_request

  # This is a blank app! Pick your first screen, build out the RCAV, and go from there. E.g.:

  # get "/your_first_screen" => "pages#first"
end

app/models/comment.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: comments
#
#  id                 :integer          not null, primary key
#  body               :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  patient_request_id :integer
#
class Comment < ApplicationRecord
  belongs_to :form, required: true, class_name: 'PatientRequest', foreign_key: 'patient_request_id'
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_patient_request
  before_action :set_comment, only: %i[show edit update destroy]
  before_action { authorize @comment || Comment }

  # GET /patient_requests/:patient_request_id/comments
  def index
    @comments = @patient_request.comments
  end

  # GET /patient_requests/:patient_request_id/comments/:id
  def show; end

  # GET /patient_requests/:patient_request_id/comments/new
  def new
    @comment = @patient_request.comments.new
  end

  # GET /patient_requests/:patient_request_id/comments/:id/edit
  def edit; end

  # POST /patient_requests/:patient_request_id/comments
  def create
    @comment = @patient_request.comments.new(comment_params)
    @comment.form.user = current_user # Ensure the comment is associated with the current user
    respond_to do |format|
      if @comment.save
        format.html { redirect_to [@patient_request, @comment], notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: [@patient_request, @comment] }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patient_requests/:patient_request_id/comments/:id
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to [@patient_request, @comment], notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: [@patient_request, @comment] }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patient_requests/:patient_request_id/comments/:id
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html do
        redirect_to patient_request_comments_url(@patient_request), notice: 'Comment was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  def set_comment
    @comment = @patient_request.comments.find(params[:id])
  end

  def set_patient_request
    @patient_request = PatientRequest.find(params[:patient_request_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <div class="d-flex justify-content-center p-3 m-3">
      <div class="card p-3" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"><%= comment.form.user.first_name %></h5>
          <p class="card-text"> <%= comment.body %></p>
        </div>
        <div class="card-footer">Created at: <%=comment.created_at%></div>
      </div>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [@patient_request, @comment]) do |form| %>
  <% if @comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% @comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="d-flex flex-column align-items-center">
  <div>
    <%= form.text_area :body, class: "form-control m-2 input-sm w-100"%>
  </div>

  <div>
    <%= form.button "Create Note", class: "btn btn-primary btn-lg bg-primary mt-4"%>
  </div>
  <%= link_to "Return to Notes", patient_request_comments_path, class: "btn btn-primary mx-auto btn-lg mt-4 mb-4" %>
<div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment, patient_request: @patient_request %>

<br>

<div>
  <%= link_to "Show comment", [@patient_request, @comment] %> |
  <%= link_to "View Comments", patient_request_comments_path(@patient_request) %>
</div>

app/views/comments/index.html.erb
<%= render 'shared/breadcrumb', breadcrumb_pages: [{ name: "Home", url: landing_page_path }, {name: "Queue", url: patient_requests_path}, {name: "Details", url: patient_request_path(@patient_request)}, {name: "Notes"}] %>
<p style="color: green"><%= notice %></p>
<h1 class="text-center">Notes</h1>
<div class="d-flex flex-column align-items-center">
  <% @comments.each do |comment| %>
    <%= render partial: 'comments/comment', locals: { comment: comment, patient_request: @patient_request } %>
  <% end %>
  <% if policy(@comments).create?%>
    <%= link_to "New Note", new_patient_request_comment_path(@patient_request), class: "btn btn-primary mx-auto btn-lg mt-4"%>
  <% end %>
  <%= link_to "Return to Details", patient_request_path(@patient_request), class: "btn btn-primary mx-auto btn-lg mt-4 mb-4"%>
</div>

app/views/comments/new.html.erb
<h1 class="text-center">New Note</h1>

<%= render "form", comment: @comment, patient_request: @patient_request%>
<br>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to 'Edit', edit_patient_request_comment_path(@patient_request, @comment) %> |
  <%= link_to 'Back', patient_request_comments_path(@patient_request) %> |
  <%= link_to 'Delete', [@patient_request, @comment], method: :delete, data: { confirm: 'Are you sure?' } %>
</div>